"""empty message

Revision ID: daaab85ae721
Revises: eda0e5f61c04
Create Date: 2019-08-08 10:29:27.479487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaab85ae721'
down_revision = 'eda0e5f61c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_verify', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('cinema_user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cinema_user_id', sa.Integer(), nullable=True),
    sa.Column('cinema_permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['cinema_user_id'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_user_permission')
    op.drop_table('permissions')
    op.drop_table('cinema_user')
    # ### end Alembic commands ###
