# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=32)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
